### ISSUE TITLE
Addition to config + issue

### ISSUE THREAD

**Issue by ghost** [dainxt/DungeonsMod-Issue-Tracker#10]
Make that you can nerf the amount of damage the bosses can do and what loot they can drop and toggle regeneration for the bosses because it is literally impossible to eliminate most of the bosses without them healing and demolishing your health despite having netherite armour.

The enchantments on the sword from the deserted doesnt do the sharpness it says it can do unless im not using it properly or smthing

**Comment by dainxt** [comment]
All bosses have been tested with their set on the wiki so its not impossible.
Also the regeneration of each boss is explained on the wiki.

Already done difficulty configuration, set customdifficulty to 1 for the easiest difficulty. Here shows how: 
https://dainxt-dungeons-mod.fandom.com/wiki/Configuration#Difficulty_configuration

Nevertheless, the boss loot will be configurable for the next update

**Comment by dainxt** [comment]
Done, added loot table changing and improve the difficulty system
