### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by harmalom** [dainxt/DungeonsMod-Issue-Tracker#12]
Forge Version
1.16.5 - 36.1.0

Crash Report
https://pastebin.com/z1yuPjiV

Log
https://pastebin.com/23Uu7Qpv

Mod List
https://pastebin.com/TatypQRJ

**Comment by thepriz** [comment]
I am getting the same crash. I just move around and then when I get close to an area the game crashes with this same error.

**Comment by dainxt** [comment]
Probably fixed on 1.3.0.

**Comment by thepriz** [comment]
I think it has been fixed. It is not crashing on me anymore in the area that it was crashing before.
