### ISSUE TITLE
Bug: y<10 structures generation

### ISSUE THREAD

**Issue by protoxos** [dainxt/DungeonsMod-Issue-Tracker#14]
After complete my firsts "Coal villager" maps, i try to get new challenges, but when get a new map, Its guides me til bedrock and theres no boss waiting for... I'm using around 100 mods, i have not idea why the first time that i follow the house map, it brings me to the boss over the desert (y>60) and the second time, the house generates under y<10

Así se ve la generación.
![image](https://user-images.githubusercontent.com/63180054/113659614-05065b80-9668-11eb-9079-20dfa2956ea1.png)

The same happens with the lab, only the top of the stairs keeps over the bedrock... (i hav'nt screenshot)

I'm using this mods...
[modlist.txt](https://github.com/dainxt/DungeonsMod-Issue-Tracker/files/6262166/modlist.txt)

With Forge 1.16.5-forge-36.1.0

Sorry for my english, i took a course on xvid...

**Comment by dainxt** [comment]
Please update, the version you are using is extremely outdated
