### ISSUE TITLE
(AOF3 - Fabric) Unable to trade with the traveller

### ISSUE THREAD

**Issue by mandrin92** [dainxt/DungeonsMod-Issue-Tracker#17]
Traveller (summoned or converted villager) keeps shaking his head and don't start the trade.
![image](https://user-images.githubusercontent.com/82092948/116783553-92827300-aa8f-11eb-871f-fc3e5fb3f7e1.png)

**Comment by dainxt** [comment]
Partially fixed. But there's a mod there that resets other villager trades. I will investigate more in detail later
