### ISSUE TITLE
Crows using 70% of my CPU time

### ISSUE THREAD

**Issue by Kinomora** [dainxt/DungeonsMod-Issue-Tracker#19]
Mod list: https://pastebin.com/hDJ6zFVy
MC version: 1.16.5
Forge version: 36.1.10
Dungeons Mod version: 1.16.3-1.3.15

Issue description:
My server slowly beings lagging harder and harder over a period of time and will continue to skip ticks the longer it goes without restarting. Using various tools like Spark mod and forge's built-in tracking, I have determined that the crows from this mod are using up 70% of my CPU time to calculate *something*.

Please review the following information:
Spark Analysis: https://spark.lucko.me/L1eVvVqXr3
command "/forge track start entity 60" was run and provided the following result: https://cdn.discordapp.com/attachments/835707004982526003/839968173545357312/unknown.png
As you can see, the crows are taking up 18,000; 14,000; and 13,000ms while a villager is taking up 150ms

Is there a way to disable the crows out-right? I am not really interested in them but I don't want to have to remove the mod if I don't have to.

**Comment by dainxt** [comment]
Probably fixed on 1.3.20.
