### ISSUE TITLE
Cant find spawn of the scientist in MC 1.16.5 

### ISSUE THREAD

**Issue by emilycodestar** [dainxt/DungeonsMod-Issue-Tracker#20]
Hello, i cant find spawn of the scientist, i try a couple ways and in creative too, but didnt find anything. Is it possible to find them, or only by spawn egg?

**Comment by dainxt** [comment]
Scientist are only founded on the crawler's dungeon.

**Comment by emilycodestar** [comment]
> Scientist are only founded on the crawler's dungeon.

Thank you for the quick answer and for this great mod :) have a nice day
