### ISSUE TITLE
Deserted killing in one hit

### ISSUE THREAD

**Issue by Gamershy** [dainxt/DungeonsMod-Issue-Tracker#21]
I'm literally equipped with full iron, the deserted is supposed to deal only 6 hearts of damage per hit according to the wiki, but he kills in one hit, making it impossible to kill him.

**Comment by dainxt** [comment]
20 Poins/2 = 10 hearts. With Full iron armor 8 hearts + player scaling(10%*player)=9 hearts rounded. Be aware that this is only on melee range, Fireballs do not apply this calculation.

**Comment by Gamershy** [comment]
Uhm, yeah no. He was killing me in one hit the moment I walked into his room, not even within melee range. Plus the water bucket doesn't work.
