### ISSUE TITLE
Shipwreck bugs.

### ISSUE THREAD

**Issue by ghost** [dainxt/DungeonsMod-Issue-Tracker#22]
### Version.
DungeonsModLite v.DungeonsModLite-1.16.5-1.0.5.jar

### What is happening.
1. The ship wrecks with the kraken has a part that has empty chest. I'm assuming this isn't what you wanted.
It is this part.
![2021-06-01_08 39 21](https://user-images.githubusercontent.com/68340265/120342291-e3ff6700-c2b4-11eb-8cf1-4fac88a307da.png)

2.The kraken despawns on player death and also if the distance between the player and the kraken are too large.

**Comment by dainxt** [comment]
Probably fixed on 1.0.11
