### ISSUE TITLE
Blank Books

### ISSUE THREAD

**Issue by Snoe0** [dainxt/DungeonsMod-Issue-Tracker#23]
Whenever I get any book from this mod, it is completely blank. Apparently there is a book in the lab that helps you beat the sun, but it was completely blank, and all the guide books were blank as well.

**Comment by dainxt** [comment]
Data like Mod version, Mod Loader is missing. Add more information to get support or this issue will be closed in 7 days

**Comment by dainxt** [comment]
1.
