### ISSUE TITLE
Had to travel 100k Blocks to fight deserted

### ISSUE THREAD

**Issue by Lavaheart626** [dainxt/DungeonsMod-Issue-Tracker#26]
I'm currently playing a modpack that uses the latest version for 1.12.2 (version 1.0.6)

I traveled about 4k blocks southwest of spawn built my house, summoned the traveller, traded for all the maps, and set out on the journey in the order of the advancements. However I ended up traveling 100k blocks northeast of spawn to fight the deserted. Which seems like an extremely unreasonable distance to travel. I passed like 4 vanilla deserts to add insult to injury on the way.

All the other maps were only like 2k blocks from my house.

**Comment by dainxt** [comment]
Sadly, 1.12.2  version of the mod is very old, and I would like to help you, but the world generation there is very archaic. There's a chance that I will not address the issue as Forge 1.12.2 was dropped support and I only adressing those issues that causes serious crashes. From here in 1 week I will advise you if the mod get an update or it will stay the same.

**Comment by dainxt** [comment]
I'm sorry, I will focus to improve Dungeons Mod for newer versions. I encourage to try the most recent mods, there's a lot of things that can be done better than on 1.12.2
