### ISSUE TITLE
Server se crashea al ir al Laboratorio (Lugar del jefe Crawler)

### ISSUE THREAD

**Issue by Adri1220** [dainxt/DungeonsMod-Issue-Tracker#27]
Al ir al DungeonsMod:The_Lab, osea el laboratorio, el lugar donde aparece el jefe Crawler, mi servidor se crashea y me bota. Así vaya caminando o haciendome tp, siempre que llego a dicha coordenada de ese lugar se crashea y no entiendo aún porque.

**Comment by dainxt** [comment]
Can you please traanslate it to english? Also you have to specify mod version and mod loader version to me to help you. If it doesn't specified in 1 week, The issue will be closed

**Comment by Adri1220** [comment]
When I go to the DungeonsMod: The_Lab, that is, the laboratory, the place where the Crawler boss appears, my server crashes and drops me. Even if I'm walking or going to the lab, every time I get to that coordinate of that place it crashes and I still don't understand why.
In DungeonsMod version 1.16.3-1.4.32

**Comment by dainxt** [comment]
Posting any crashlogs also would be useful
