### ISSUE TITLE
Book override

### ISSUE THREAD

**Issue by ghost** [dainxt/DungeonsMod-Issue-Tracker#30]
Hi, i got script for giving items at start like ftbquests book, after update, every re-log into a world, the ftbquest book dissapear/ovveride by duneonsmod book,

Can you make a config for it or give any idea how to fix it?

**Comment by dainxt** [comment]
Probably fixed on 1.0.12, let me know if possible

**Comment by ghost** [comment]
Sorry i forgot about it, its fixed, btw I was just adding a worldgen remove script for mob spawn and saw your update so im appreciate how fast you resolve the problems ;) 

thanks!
