### ISSUE TITLE
Cannot locate structures and heavy tps lag + crash when interacting with traveler

### ISSUE THREAD

**Issue by InteJason** [dainxt/DungeonsMod-Issue-Tracker#31]
I notice that you mentioned an issue with cavesbiomes api. So this issue may have something to do with that as my modpack runs caves and cliffs backport mod along with this mod.

1) /locate cannot locate any dungeonsmod structures

2) When interacting with traveler, heavy tps lag spikes occurs, here's a spark log: https://spark.lucko.me/VsnCHLnagO
Furthermore, it crashes occasionally: https://pastebin.com/27SmjGvh

3) As for the issue mentioned in cavesbiomes api, i found that most structures from other mods such as stoneholm, dungeons crawl now spawn with the new cavesbiomes api update.

**Comment by dainxt** [comment]
Thank you for the information, Fixed on 1.4.40
