### ISSUE TITLE
Mob Spawns

### ISSUE THREAD

**Issue by ghost** [dainxt/DungeonsMod-Issue-Tracker#35]
Hello,
I cant disable mobs, rogue and ants, even if i set the spawn to 0, can you check whats going on?

thanks

**Comment by dainxt** [comment]
Specify version

**Comment by ghost** [comment]
14 latest

W dniu pt., 10.09.2021 o 18:25 dainxt ***@***.***> napisał(a):

**Comment by dainxt** [comment]
???, I mean, mod version and Forge or Fabric version.

**Comment by ghost** [comment]
Fabric
