### ISSUE TITLE
[1.16.5] Void Master seem unkillable

### ISSUE THREAD

**Issue by Zarkov2** [dainxt/DungeonsMod-Issue-Tracker#36]
Mod version: 1.16.3_1.4.40 (from file name)
Mod pack: Seaopolis 7.4 for MC 1.16.5

When fighting the Void Master, using 100+ Instant Damage II arrows with a Power V enchanted Mekanism bow having fire mode enabled, didn't cause any visible damage on the health bar. The arrows were all targeted at the large center eye. It did flash red indicating that the arrow hits were being registered.

If this mob behavior is unintended, a possible reason could be that the first ender eye I used at an end gateway after killing the dragon spawned the counterpart gateway and me right outside the Void Master building, immediately causing the health bar to become visible and shortly after me to start taking damage from its attacks through the building wall. I'm guessing that is an unusual way for it to be initially triggered which perhaps could cause issues.

**Comment by dainxt** [comment]
Read the wiki https://dainxt-dungeons-mod.fandom.com/wiki/Void_Master, especially the passives.
