### ISSUE TITLE
Traveler doesn't spawn

### ISSUE THREAD

**Issue by Simplebenja** [dainxt/DungeonsMod-Issue-Tracker#39]
When I try to summon the Traveler, it does not appear, not with a coal block, not with a burning coal block, the coal block does not transform a villager into a Traveler, nothing, I cannot make the Traveler appear.

The config for Traveler spawn is set to true

![2021-10-14_10 02 52](https://user-images.githubusercontent.com/92282280/137347142-f4cea0e5-92b1-457d-98f7-533f7ae5731a.png)
![2021-10-14_10 07 09](https://user-images.githubusercontent.com/92282280/137347180-a56bc63c-73ad-45b8-a440-87bf4de25d4c.png)
![2021-10-14_10 07 34](https://user-images.githubusercontent.com/92282280/137347184-19dbc3ba-f6e5-4d6b-96b1-6d19080b1c11.png)
![2021-10-14_10 07 37](https://user-images.githubusercontent.com/92282280/137347189-28cb73ac-8735-4936-9864-eda4820f64dd.png)

[latest.log](https://github.com/dainxt/DungeonsMod-Issue-Tracker/files/7347326/latest.log)

Launcher: TLauncher 2.82
Java: Version 8 actualization 301 compilation 1.8.0_301-b09
Minecraft 1.17.1
Forge 37.0.84
Dungeons Mod version: DungeonsMod-1.17.1-1.4.53

**Comment by dainxt** [comment]
https://dainxt-dungeons-mod.fandom.com/wiki/Getting_Started Invocation changed use the haycoal one

**Comment by Simplebenja** [comment]
sorry, my fault

in that case I suggest mentioning it on the forge page

**Comment by dainxt** [comment]
Done
