### ISSUE TITLE
Incompatibility with Dungeon Crawl and Valhelsia structures

### ISSUE THREAD

**Issue by Mingu2209** [dainxt/DungeonsMod-Issue-Tracker#4]
Hi,

I added your mod in my server to try and I loved it. The problem is that if I add Dungeons Craw and Valhelsia structures, I can't see any of these structures anymore created in the world, only yours. Could you make it compatible? There is one person staying the same issue in this mod page (not in issues).

More info:

Forge version: 34.1.19
Dungeon mod: DungeonsMod-1.16.3-1.0.10.jar

I would lo have in my server all 3 mods appearing :)

Thanks in advance!

**Comment by dainxt** [comment]
This have been fixed on 1.16.3-1.0.11 please update
