### ISSUE TITLE
[1.17.1] Crash when player died at The Origin java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122424_()" because "signFacing" is null

### ISSUE THREAD

**Issue by ProsperCraft** [dainxt/DungeonsMod-Issue-Tracker#40]
On my [TownCraft THREE 1.17.1](https://www.curseforge.com/minecraft/modpacks/towncraft) testing modpack a player on our dedicated server used a lost tablet  from the Tombstone mod.

He said he was being hit with a beam that kept getting strong until he died.  When he died the server kicked all of the players and spit out some stacktracing then locked up.
Watchdog caught it after 7 mins and produced some more stacktraces which I have attached.

Here is the first crash report.
https://gist.github.com/ProsperCraft/e7a994b83bf7fd6085e1ef28e0734f7d

The server log is 330 megs due to Toms Storage mod bug, and doesn't include the watchdog stacktraces.

Here is the watchdog stacktrace-
https://gist.github.com/ProsperCraft/e824fcf36dedebf9c600bca480eff1b5

**Comment by dainxt** [comment]
Fixed in 1.4.55
