### ISSUE TITLE
Kraken will get stuck on gravestones, compatibility issue

### ISSUE THREAD

**Issue by maxzero77** [dainxt/DungeonsMod-Issue-Tracker#41]
the kraken boss will get you on a deathloop if you have the gravestones mod installed, the gravestone will spawn inside the kraken making it get stuck, the gravestone cant be broken unless the kraken grabs you, at which point you cannot escape.

**Comment by dainxt** [comment]
Need more information as: If you are using Fabric or Forge, which Minecraft version you are using and which is the mod version as well

**Comment by dainxt** [comment]
As no more information was provided, this issue will be closed
