### ISSUE TITLE
Mimics Extreme spawning

### ISSUE THREAD

**Issue by MrBloodworth** [dainxt/DungeonsMod-Issue-Tracker#47]
There is an Extreme amount of Mimic Chests spawning near all dungeons added by this mod. They are spawning in like regular mobs, already moving. They do no use an expected "Mimic Chest" behavior of impersonating a lootable chest, THEN attacking/Moving.  The Crawler Lab center is over run with mimics. There is no way to adjust spawn rates.

I Do love that they use the resource pack textures!.

DungeonsMod-1.18-1.4.60
Forge 1.18.1-39.0.20
![Mimics](https://user-images.githubusercontent.com/96947832/149625073-7ce1e766-93c7-4561-8dbd-50d5553b485d.jpg)

**Comment by dainxt** [comment]
You can adjust the spawn weight, reduce it for lesser spawning, sorry for the late response
