### ISSUE TITLE
Can't connect to my Server.

### ISSUE THREAD

**Issue by smallerYeet** [dainxt/DungeonsMod-Issue-Tracker#5]
Mc Version: 1.16.3
Forge Version: 34.1.42
Mod Version: 1.1.2
[latest.log](https://github.com/dainxt/DungeonsMod-Issue-Tracker/files/5654144/latest.log)
[debug.log](https://github.com/dainxt/DungeonsMod-Issue-Tracker/files/5654145/debug.log)

So when I try to join my server it has a weird error.
![grafik](https://user-images.githubusercontent.com/68237474/101382255-068d6600-38b8-11eb-83b7-fdc9710fb772.png)
I think it's because:
"[18:13:45] [Netty Client IO #1/ERROR] [minecraft/WorldSettingsImport]: Error adding element: Unknown registry element com.dainxt.dungeonsmod.world.gen.feature.ExampleFeature@40d97970"

I don't know much about logs etc, there is an error with this mod so here I am.

**Comment by dainxt** [comment]
That error is not related to networking. You should check lastest logs on the server when you connect as probably could be an external issue.

**Comment by smallerYeet** [comment]
The issue is fixed, sorry for writing. Normally I wait on a Discord for them to send me feedback, that what I should have done.
Sorry!
