### ISSUE TITLE
Lonely villager

### ISSUE THREAD

**Issue by Minecraftme999** [dainxt/DungeonsMod-Issue-Tracker#50]
I tried spawing the villager in 1.16.3  but it was not working and i tried many times I dont know if the way to spawn it was changed but from what i heard your supposed to light a coal block on fire

**Comment by dainxt** [comment]
https://dainxt-dungeons-mod.fandom.com/wiki/Getting_Started Now the invocation is done with haycoal and a campfire, refer to the wiki to see how
