### ISSUE TITLE
Spectral arrow invocation??

### ISSUE THREAD

**Issue by ELBEANS199** [dainxt/DungeonsMod-Issue-Tracker#6]
Some friends and myself opened a server recently with some mods, including this one, and yesterday we found the lab dungeon which we cleaned up and found a book that seems to have some kind of invocation ritual, we tried to make it but didn't work, know why?? maybe we are doing it wrong? I post an image of the book
![postear](https://user-images.githubusercontent.com/76273226/102704852-242bd980-4281-11eb-9aa4-42e83ec5dfae.png)

**Comment by ELBEANS199** [comment]
(we tried to use the spectral arrow, ofc)

**Comment by dainxt** [comment]
This is not a bug, is a faq. This is not how to invoke the sun. You can go to the discord server if you want more info.
