### ISSUE TITLE
Concerning Forge Energy Generation

### ISSUE THREAD

**Issue by Adstrum** [dainxt/DungeonsMod-Issue-Tracker#7]
I spent the better part of an hour looking into trying to generate FE for **Refined Storage**'s Controller and came to the conclusion that, unless I invested time into looking at every mod's contributions to the modpack and found something I'm probably missing, I cannot find a way to generate Forge Energy in this modpack, which renders Refined Storage completely useless for me 😕 

So TL:DR,
How do I generate FE?

**Comment by dainxt** [comment]
Wut? This mod does not relate to FE
