### ISSUE TITLE
[1.16.5] The Deserted Boss Glitching out

### ISSUE THREAD

**Issue by Blu3M4n97** [dainxt/DungeonsMod-Issue-Tracker#8]
Minecraft version: 1.16.5
Forge version: 36.0.42
Mod version: DungeonsMod-1.16.3-1.2.6

When trying to kill the boss "The Deserted" it glitches out when near death. It teleports a few blocks away, sometimes underground, and for some reason "deletes" some blocks just before going underground. And after teleporting away it restores full health. Only way it could be killed was with the command /kill.

Don't know if this also helps, but I was also using a mod FunMod that has a custom sword with which I tried to kill the boss.

Edit: When the boss is near death (supposed to be dead) and before teleporting away and restoring its full health, it drops FunMod mod lootbag.

**Comment by dainxt** [comment]
Probably fixed in 1.2.10

**Comment by Blu3M4n97** [comment]
> Probably fixed in 1.2.10

Yes, it is fixed now.
